name: LFS Warning

on:
  pull_request:
    types: [assigned, opened, edited, reopened, synchronize, ready_for_review]

permissions: read-all

jobs:
  large-file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actionsdesk/lfs-warning@e5f9a4c21f4bee104db7c0f23954dde59e5df909 # v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filesizelimit: 10MB
          labelName: lfs-warning
          exclusionPatterns: |
            cli/slsa-verifier/testdata/**
