name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3

      - name: setup-go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3
        with:
          go-version: '1.17'

      - name: Run tests for verifier
        run: |
          set -euo pipefail

          go mod vendor
          # Build
          go build -mod=vendor
          # Tests
          go test -mod=vendor -v ./...
